-- CHATROOMS
INSERT INTO CHATROOMS(CHATROOM_TITLE, CHATROOM_LOCATION) VALUES ('되나요되나요', '로케이션');

-- CHAT_MESSAGES
INSERT INTO CHAT_MESSAGES(CHAT_MESSAGE_CONTENT, CHATROOM_ID) VALUES ('테스트', '1');
INSERT INTO CHAT_MESSAGES(CHAT_MESSAGE_CONTENT, CHATROOM_ID) VALUES ('테스트222', '1');